# syntax=docker/dockerfile:1

# Usage
# podman build --file apps/greet/Containerfile -t greet:0.1.0 .

# === Stage 1: just your already-built binary ===
# (you can skip this if you want to build inside Docker, but since you already have the binary...)
FROM scratch AS binary-source

# Copy the compiled binary
COPY ./target/x86_64-unknown-linux-musl/release/greet /greet